### ISSUE TITLE
Settings panel subnav has white background on themes full mode (v4)

### ISSUE THREAD

**Issue by csalmeida** [csalmeida/protonmail-themes#33]
Themes on version `v4.0.0` have a white background on the settings panel `.subnav`. This can be replicated by clicking *Settings* and *Appearance* whilst logged into a PM account.

At a glance it looks like adding the following block to `templates/@theme-base/_full.scss`:

```scss
// Settings subnav
.subnav {
 background: lighten($base, 5%);
}
```

It currently looks like this (using the Dark Bubble Gum theme):
<img width="373" alt="70156060-3d300f80-16ab-11ea-8cdc-05639410c7e0" src="https://user-images.githubusercontent.com/12223613/70374997-16fbb100-18f1-11ea-85ee-b2c7e62678c5.png">
